language: ruby
os:
  - linux
  - osx
  - windows

sudo: true # need this for libgirepository1.0-dev

addons:
  apt:
    packages:
      - libgirepository1.0-dev # for gobject-introspection
rvm:
  - 2.4.2
  - 2.5.3
  - 2.6.5
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
