# before_install:
#   - gem update --system
#   - gem install bundler

jobs:
  include:
    - os: windows
      language: bash
      install:
        - gem install bundler
        - bundle install
      script: bundle exec rake
    - os: linux
      language: ruby
      rvm: 2.4.2
      script: bundle exec rake
    - os: linux
      language: ruby
      rvm: 2.5.3
      script: bundle exec rake
      addons:
        apt:
          packages:
            - libgirepository1.0-dev # for gobject-introspection
    - os: linux
      language: ruby
      rvm: 2.6.5
      script: bundle exec rake
      addons:
        apt:
          packages:
            - libgirepository1.0-dev # for gobject-introspection
    - os: linux
      language: ruby
      rvm: ruby-head
      allow_failures: true
      script: bundle exec rake
      addons:
        apt:
          packages:
            - libgirepository1.0-dev # for gobject-introspection
